### ISSUE TITLE
Nft add element filter = No such file or directory

### ISSUE THREAD

**Issue by keebs** [azlux/nft-dns#1]
I'm not an nftables expert, but the "nft add element filter" command appears to fail with nftables vv1.0 6. Nftables wants a table type, such as "nft add element inet filter"

**Comment by azlux** [comment]
Hi,
That shouldn't be the full command the code run. A part is missing.
Can you paste your custom config file you use ?
Can you run the programm manually with the parameter ` /opt/nft-dns/nft-dns.py --verbose ` to have more output ?

**Comment by keebs** [comment]
2024-01-11 16:44:40,798 INFO:Reading config file : /etc/nft-dns.conf
2024-01-11 16:44:40,799 INFO:Only config file with prefix .conf is read
2024-01-11 16:44:40,799 INFO:Reading config directory : /etc/nft-dns.d
2024-01-11 16:44:40,799 INFO:# Parsing the configuration
2024-01-11 16:44:40,799 DEBUG:set_name='IPsAapt4' typeof=4 fqdn='deb.debian.org' ip_list=None ttl=None next_update=None
2024-01-11 16:44:40,799 DEBUG:set_name='IPsAapt4' typeof=4 fqdn='security.debian.org' ip_list=None ttl=None next_update=None
2024-01-11 16:44:40,800 DEBUG:Command to run : nft list set filter IPsAapt4
2024-01-11 16:44:40,805 ERROR:
2024-01-11 16:44:40,805 ERROR:Error: No such file or directory
list set filter IPsAapt4
         ^^^^^^

Traceback (most recent call last):
  File "/opt/nft-dns/nft-dns.py", line 191, in <module>
    main()
  File "/opt/nft-dns/nft-dns.py", line 172, in main
    read_config()
  File "/opt/nft-dns/nft-dns.py", line 75, in read_config
    if "ipv4_addr" in res or "ipv6_addr" in res:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable


I'm working from the command line to troubleshoot at the moment. There is no custom config file.

Your command is this:
        run_command(f"nft add element filter {one_entry.set_name} {{{', '.join([str(ip) for ip in one_entry.ip_list])}}}")

Which should create a statement like:
nft add element filter blackhole { 127.0.0.1 }

This results in the error:
Error: No such file or directory; did you mean table ‘filter’ in family inet?
add element filter blackhole { 127.0.0.1 }

The proper command that is successful is:
nft add element inet filter blackhole { 127.0.0.1 }

I'm using the current nftables version 
nftables v1.0.6 (Lester Gooch #5)

**Comment by azlux** [comment]
From the v1.0.6 , the command is now : `nft list set ip filter IPsAapt4`  (ip and filter depend of your config.
Can you output the result of `nft list sets` I think I need the rework the logic of my checks.

**Comment by keebs** [comment]
# nft list sets
table inet filter {
        set blackhole {
                type ipv4_addr
                flags interval
                elements = { 127.0.0.1 }
        }
}

**Comment by keebs** [comment]
The correct command would be:

nft list set inet filter blackhole
table inet filter {
        set blackhole {
                type ipv4_addr
                flags interval
                elements = { 127.0.0.1 }
        }
}

It would appear that there should be two additional configurations in nft-dns.conf: 'table' and 'family'
as we could need to resolve FQDNs in the output table or even a custom table.
Also, there are 6 possible families. In my case, my current table family is inet, but it could be ip, ip6, etc.

**Comment by azlux** [comment]
wait, If you want nft-dns to fill the `blackhole` named set, you need to add this information into the config : https://github.com/azlux/nft-dns/blob/main/MANUAL.md#other-sections `set_name` part.

According to your log, currently, the script try to fill the set named `IPsAapt4`. And it don't exist, that why nft say the command isn't found.
TODO : I need to make an check improve to have a better error.

**Comment by keebs** [comment]
Sorry for the confusion - I was testing multiple scenarios and crossed the examples.

My current nftables configurtion:
```
table inet filter {
   set IPsApt4 {
      type ipv4_addr
      flags interval
      elements = { 127.0.0.1 }
   }
   ...
```

My current nft-dns configuration:
```
[GLOBAL]
#max_ttl = 86400
#min_ttl = 300
#mode = capture
#custom_resolver = "1.1.1.1"
#dry_run = False
#verbose = False
include_config_dir = /etc/nft-dns.d/

[test]
set_name = IPsApt4
enable = true
typeof = ipv4
domains = deb.debian.org, security.debian.org
```

```console
foo@bar:~$ /opt/nft-dns/nft-dns.py --verbose
2024-01-12 13:55:06,450 INFO:Reading config file : /etc/nft-dns.conf
2024-01-12 13:55:06,451 INFO:Only config file with prefix .conf is read
2024-01-12 13:55:06,451 INFO:Reading config directory : /etc/nft-dns.d
2024-01-12 13:55:06,451 INFO:# Parsing the configuration
2024-01-12 13:55:06,452 DEBUG:set_name='IPsApt4' typeof=4 fqdn='deb.debian.org' ip_list=None ttl=None next_update=None
2024-01-12 13:55:06,452 DEBUG:set_name='IPsApt4' typeof=4 fqdn='security.debian.org' ip_list=None ttl=None next_update=None
2024-01-12 13:55:06,452 DEBUG:Command to run : nft list set filter IPsApt4
2024-01-12 13:55:06,478 ERROR:
2024-01-12 13:55:06,478 ERROR:Error: No such file or directory
list set filter IPsApt4
         ^^^^^^

Traceback (most recent call last):
  File "/opt/nft-dns/nft-dns.py", line 191, in <module>
    main()
  File "/opt/nft-dns/nft-dns.py", line 172, in main
    read_config()
  File "/opt/nft-dns/nft-dns.py", line 75, in read_config
    if "ipv4_addr" in res or "ipv6_addr" in res:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

```

```console
foo@bar:~$ nft list sets
table inet filter {
        set IPsApt4 {
                type ipv4_addr
                flags interval
                elements = { 127.0.0.1 }
        }
}
```

```console
foo@bar:~$ nft list set filter IPsApt4
Error: No such file or directory
list set filter IPsApt4
         ^^^^^^
```

```console
foo@bar:~$ nft list set inet filter IPsApt4
table inet filter {
        set IPsApt4 {
                type ipv4_addr
                flags interval
                elements = { 127.0.0.1 }
        }
}
```

```console
foo@bar:~$ nft add element filter IPsApt4 { 127.0.0.1 }
Error: No such file or directory; did you mean table ‘filter’ in family inet?
add element filter IPsApt4 { 127.0.0.1 }
            ^^^^^^
```

```console
foo@bar:~$ nft add element inet filter IPsApt4 { 127.0.0.1 }
foo@bar:~$
```

```console
foo@bar:~$ nft delete element filter IPsApt4
Error: syntax error, unexpected newline, expecting '{' or '$'
delete element filter IPsApt4
                             ^
```

```console
foo@bar:~$ nft delete element inet filter IPsApt4 { 127.0.0.1 }
foo@bar:~$
```

**Comment by azlux** [comment]
Ok, I see now, something have change.
So I will make an update, maybe next week because I don't have my computer free this week-end.

If you know python3, you can make a PR, the issue is here : https://github.com/azlux/nft-dns/blob/main/nft-dns.py#L73-L79
When reading the config file, I check if the named set exist or I exit on error.

This need to be change because nftables now need the "table" name to add/update/delete an element into a "named set". Maybe an additional option, or searching it with the command "nft list sets"

**Comment by keebs** [comment]
I can code it, but no sense to reinvent the wheel when you did a perfectly fine job. I agree with the lines you provided,  but also Lines 127 and 130 have to be formatted with the table family. Thanks!

**Comment by azlux** [comment]
Can you try the new release, the config have change a little.
https://github.com/azlux/nft-dns/releases/tag/0.4

I don't use typeof config, but family to catch the good table.

**Comment by keebs** [comment]
That looks to be working great, now. Thank you! If I could make another suggestion, add the table as another configuration option. Maybe default to filter.

**Comment by azlux** [comment]
will be added with the commit https://github.com/azlux/nft-dns/commit/bf5e55a08a8b76c6561897981f413186944f021e can you test the next release ?

**Comment by keebs** [comment]
I haven't tried a lot of intricate configurations, yet, but looks good so far! Nice work! Thanks!
