### ISSUE TITLE
Integrating with existing rules that use the inet family

### ISSUE THREAD

**Issue by ghost** [azlux/nft-dns#3]
Very nice work!

I finally got things running by changing my 'filter' table to 
`table inet my_filter to table ip my_filter` 

inet is used to specify both families: ipv4 and ipv6

Is "inet" easy to add to your code? Not a really important issue but just wondering.

I am not a Python superstar :)

**Comment by azlux** [comment]
You can specify the family with the `family`config section : https://github.com/azlux/nft-dns/blob/main/MANUAL.md#other-sections

**Comment by ghost** [comment]
Thanks, I will try that.

**Comment by ghost** [comment]
That works. I must have been doing something stupid :)

So this is my config...

cat /etc/nft-dns.conf

[GLOBAL]
#max_ttl = 86400
#min_ttl = 300
#mode = capture
#custom_resolver = "1.1.1.1"
#dry_run = False
#verbose = False
#include_config_dir = /etc/nft-dns.d/

[debian]
set_name=allow_dyndns
enable= true
family= inet
table = my_filter
domains = mysite.example.com
and this is my nftables.conf

table inet my_filter {

set allow_dyndns {
type ipv4_addr;
elements = { 8.8.8.8 } ;
}

set not_my_ssh {
type ipv4_addr;
flags dynamic;
size 65536;
timeout 10m;
}

set my_drops {
type ipv4_addr;
flags dynamic;
size 65536;
timeout 10m;
comment "Hosts Rejected";
}

chain my_input {
type filter hook input priority 0; policy drop;

ct state invalid drop

# input interface name
iifname lo accept

ip saddr @allow_dyndns counter accept

ct state established,related counter accept

# uncomment for certbot to work
#tcp dport 80 counter accept
#tcp dport 443 counter accept

ip protocol udp update @my_drops { ip saddr counter } drop
ip protocol tcp update @my_drops { ip saddr counter } drop
drop
###################################################################################
# done dropping
###################################################################################
}

# forward
chain my_forward {
type filter hook forward priority 0; policy accept;
}

# output
chain my_output {
type filter hook output priority 0; policy accept;
}
}

# eof
